---
title: "rtmbGMACS CTL: allometry specification"
author:
- name: William T. Stockhausen
  affiliations:
    - id: afsc-refm
      name: "Alaska Fisheries Science Center"
      department: "Resource Ecology and Fisheries Management"
      address: 
        - "7600 Sand Point Way N.E."
        - "Seattle, Washington 98115-6349"
date: '`r format(Sys.time(), "%b %e, %Y")`'
fontsize: 11pt 
number-sections: true
number-depth: 2
reference-location: document
bibliography: '`r path.expand("~/Work/Projects/Bibliography/AllRefs.bib")`'
csl: '`r system.file("files/CJFAS.csl",package="wtsQMD")`'
link-citations: true
crossref:
  chapters: false      # prepend label reference numbers by chater number?
  fig-title: Figure    # for caption: default is "Figure")
  tbl-title: Table     # for caption: default is "Table")
  title-delim: "."     # for caption: default is ":")
  fig-prefix: Figure   # for in-text (use [-@fig-ref] to drop prefix in text)
  tbl-prefix: Table    # for in-text (use [-@tbl-ref] to drop prefix in text)
  fig-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  tbl-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  subref-labels: alpha a # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  ref-hyperlink: true    # references are hyperlinked if true
format: 
  html: 
    df-print: paged
    toc: true
    toc-location: right
    fig-width: 8
    fig-asp: 0.4
    fig-dpi: 100
    embed-resources: true
    include-in-header: 
      - '`r system.file("files/in-line_math_mode.html",package="wtsQMD")`'
  pdf:
    documentclass: scrartcl
    toc: false
    fig_crop: false
    keep-tex: false
    geometry:
      - left=1.0in
      - right=1.0in
      - top=1.0in
      - bottom=1.0in
      - textwidth=6.5in
      - showframe=false
    include-in-header: 
       #include '\usepackage{nopageno}' below in header to turn off page numbering
      - text: |
          \usepackage{placeins}
          \extrafloats{500}
          \maxdeadcycles=10000
          \usepackage{fontspec}
          \usepackage{multicol}
          \usepackage{hhline}
          \newlength\Oldarrayrulewidth
          \newlength\Oldtabcolsep
          \usepackage{nopageno}
      - file: '`r system.file("files/ltx_ExtraLatexIncludes.tex",package="wtsQMD")`'
echo: false
warning: false
results: 'hide'
keep-md: true
keep-yaml: false
editor: source
editor_options: 
  chunk_output_type: console
concordance: true
params:
  setup: !expr 'system.file("files/qmd_setup.R",package="wtsQMD")'
  testing: false
  reorderTables: false   #--issue with finding "range" of table values  (don't use)
  reorderFigures: false  #--issue with finding "range" of figure values (don't use)
---
<!-- IMPORTANT: if used as a child doc, all chunk labels must be unique within the overall document -->

<!-- 
  NOTEs: 
     * child_path$peek() gives path to current script.
     * before starting a child document, do 
         "child_path$push(file.path(child_path$peek(),rel_path))" first, 
         where rel_path is the relative path to the child
     * after a child document has finished, do "child_path$pop()" to return to current path value
-->

<!-- if not child doc, set up required objects -->
```{r}
#| label: CTL-Allometry_setup
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  testing = params$testing;
  if (testing) cat(params$setup,"\n\n")
  source(params$setup);
  if (testing) cat("root = ",root,"\n\n")
  reorderTables  = params$reorderTables;
  reorderFigures = params$reorderFigures;
```

```{r}
#| label: setup_CTL-Allometry
#| results: asis
  require(rtmbGMACS);
  require(ggplot2);
  require(kableExtra);
  require(tables);
  thm = wtsPlots::getStdTheme();
  options("readr.show_col_types"=FALSE);
  if (testing) cat("dirThs =",child_path$peek(),"\n\n")
  if (!exists("tblno")) tblno = 0;#--index in LETTERS for tables in text
```

```{r}
#| label: CTL-Allometry-ModelDimensions
#| eval: !expr '!knitr::opts_knit$get("child")'
vRs="EBS";
miz = as.character(seq(25,75,5));
mmz = as.character(seq(50,75,5));
fiz = as.character(seq(25,65,5));
fmz = as.character(seq(30,65,5));
vXs=list(male=list(imm=list(`new`=miz,
                             `old`=miz),
                    mat=list(`new`=mmz,
                             `old`=mmz,
                             `very`=mmz)
                  ),
          female=list(imm=list(`new`=fiz,
                               `old`=fiz),
                      mat=list(`new`=fmz,
                               `old`=fmz)
                     )
         ); attr(vXs,"dmnms")<-c("x","m","p","z");
ys = as.character(2015:2024); names(ys) = ys;
ss = as.character(1:2);       names(ss) = ss;
dmsC    = createSparseDimsMap(r=vRs,x=vXs);            #--DimsMap for stock categories
dmsYS   = createSparseDimsMap(y=ys,s=ss);              #--DimsMap for years and seasons
dmsYSC  = createSparseDimsMap(y=ys,s=ss,r=vRs,x=vXs);  #--DimsMap for combination 
dimsZBC = dmsC |> dplyr::mutate(lft=as.numeric(z)-2.5,mid=as.numeric(z),rgt=as.numeric(z)+2.5);
fleets = c("Directed","Bycatch","Survey"); #--fishery and survey fleets
```

### Allometry {#sec-Allometry}

The following options are available to define allometry in the model:

  - 
  
```{r}
#| label: CTL-Allometry1
#| echo: true
str<-paste0('
  #--rtmbGMACS allometry specifications----
  PROCESS_ALLOMETRY
  CODE
  mfAll  = dmsYSC;
  mf2024 = dmsYSC |> dplyr::filter(y=="2024");
  contr_none = "FALSE";
  contr_sum  = list(x="contr.sum",m="contr.sum");
  END_CODE
  FUNCTIONS
  fcn_idx  fcn_id     function  frame    params              vars    description 
    1      pwrLaw1     pwrLaw1   mfAll   pA,pB1                z      w(z)_=_pA_*_(z^pB1)
    2      pwrLaw2     pwrLaw2   mf2024  pLnA,pLnS,pB2,pZ0     z      w(z)_=_exp(pLnA+pLnS+pB2*ln(z/pZ0))
  END_FUNCTIONS
  PARAM_EQS
  par_idx  fcn_idx par_id  feEQs   feCons       feLink   reEQs reCovType reLink   ecEQs  ecLink
   1         1      pA     ~1+x*m  contr_sum     add      NA       NA       NA      NA     NA
   2         1      pB1    ~0+x:m  contr_none    add      NA       NA       NA      NA     NA
   3         2      pLnA   ~0+x    contr_none    add      NA       NA       NA      NA     NA
   4         2      pLnS   ~0+x    contr_none    add      NA       NA       NA      NA     NA
   5         2      pB2    ~0+x    contr_none    add      NA       NA       NA      NA     NA
   6         2      pZ0    ~0+x    contr_none    add      NA       NA       NA      NA     NA
  END_PARAM_EQS
  FE_VALS
  pA
  pv_idx  par_idx  x        m     mirror  phase    units     IV
   1      1        male     imm     0      -1     grams     0.00027
   2      1        male     mat     1
   3      1        female   imm     0      -1     grams     0.000562
   4      1        female   mat     0      -1     grams     0.000441
  END_pA
  pB1
  pv_idx  par_idx  x        m     mirror   phase    units     IV
   1      2        male     imm     0       -1     none      3.022134
   2      2        male     mat     1       
   3      2        female   imm     0       -1     none      2.816928
   4      2        female   mat     0       -1     none      2.898686
  END_pB1
  pLnA
  pv_idx  par_idx  x     phase    units     tform  IV
   1      3     male      -1      grams     log    0.00027
  END_pLnA
  pLnS
  pv_idx  par_idx  x     phase    units     IV
   1      4     male      -1      none      0.0000
  END_pLnS
  pB2
  pv_idx  par_idx  x     phase    units     IV
   1      5     male      -1      none      3.022134
  END_pB2
  pZ0
  pv_idx  par_idx  x     phase    units     IV
   1      6     male      -1      mm_CW     1.00000
  END_pZ0
  END_FE_VALS
  END_ALLOMETRY
');
strv = str |> splitText() |> extractLines("PROCESS_ALLOMETRY","END_ALLOMETRY");
strv |> extractLines("CODE","END_CODE") |> evalTextAsCode();
dfrFcns = strv |> extractLines("FUNCTIONS","END_FUNCTIONS")   |> evalTextAsDataframe();
dfrPEQs = strv |> extractLines("PARAM_EQS","END_PARAM_EQS")   |> evalTextAsDataframe();
par_ids = dfrPEQs$id;
##--fixed effects parameter values
strFEVs = strv |> extractLines("FE_VALS","END_FE_VALS");
lstFEVs = list();
if (length(strFEVs)>0){
  for (par_id in par_ids){
    strp = strFEVs |> extractLines(par_id,paste0("END_",par_id));
    lstFEVs[[par_id]]  = strp |> evalTextAsDataframe();
  }
}#--FEVs
##--random effects parameter values
strREVs = strv |> extractLines("RE_VALS","END_RE_VALS");
lstREVs = list();
if (length(strREVs)>0){
  for (par_id in par_ids){
    strp = strREVs |> extractLines(par_id,paste0("END_",par_id));
    lstREVs[[par_id]]  = strp |> evalTextAsDataframe();
  }
}#--REVs
##--environmental covariates parameter values
strECVs = strv |> extractLines("EC_VALS","END_EC_VALS");
lstECVs = list();
if (length(strECVs)>0){
  for (par_id in par_ids){
    strp = strECVs |> extractLines(par_id,paste0("END_",par_id));
    lstECVs[[par_id]]  = strp |> evalTextAsDataframe();
  }
}#--ECVs

#--determine model matrices
tbl = dfrFcns |> dplyr::full_join(dfrPEQs,by="fcn_idx");
idxFE = idxEC = idxRE = 0;
lstModMtx = list();
for (par_idx_ in tbl$par_idx){
  #--testing: par_idx_ = 1;
  rw = tbl |> dplyr::filter(par_idx==par_idx_);
  #--fixed effects
  lstModMtxFEs = calcModelMatrixFEs(rw$feEQs,dfrMF=get(rw$frame),ctrs=get(rw$feCons));
  idxFE = idxFE + lstModMtxFEs$npars;
  lstModMtxFEs$idx_end = idxFEs;
  #--env. covariates
  lstModMtxECs = calcModelMatrixFEs(rw$ecEQs,dfrMF=get(rw$frame));
  idxEC = idxEC + lstModMtxECs$npars;
  lstModMtxECs$idx_end = idxECs;
  #--random effects
  lstModMtxREs = calcModelMatrixREs(rw$reEQs,dfrMF=get(rw$frame),cov_type=rw$reCovType);
  idxRE = idxRE + lstModMtxREs$npars;
  lstModMtxREs$idx_end = idxREs;
  #--combine lists into one object
  lstModMtx[[rw$par_id]] = list(FEs=lstModMtxFEs,ECs=lstModMtxECs,REs=lstModMtxREs);
}
lstAllom = list(lstModMtx=lstModMtx, nparFEs=idxFE, nparECs=idxEC, nparREs=idxRE);
```

```{r}
#| label: CTL-Allometry2
#| echo: true
str<-paste0('
  #--rtmbGMACS allometry specifications----
  PROCESS_ALLOMETRY
  MODEL_FRAMES
  {mfALL  = dmsYSC;}
  {mf2024 = dmsYSC |> dplyr::filter(y=="2024");}
  END_FRAMES
  FUNCTIONS
  fcn_idx  id        function  frame   params              vars  description 
    1    pwrLaw1   pwrLaw1   mfAll   pA,pB1                z   w(z)_=_pA_*_(z^pB)
    2    pwrLaw2   pwrLaw2   mf2024  pLnA,pLnS,pB2,pZ0     z   w(z)_=_exp(pLnA+pLnS+pB*ln(z/pZ0))
  END_FUNCTIONS
  PARAM_EQS
  par_idx  fcn_idx  id    eEQs    feCons        feLink   reEQs reCovType reLink   ecEQs  ecLink
   1         1     pA     ~0+x:m  contr_none    add      NA       NA      NA      NA     NA
   2         1     pB1    ~0+x:m  contr_none    add      NA       NA      NA      NA     NA
   3         2     pLnA   ~0+x    contr_none    add      NA       NA      NA      NA     NA
   4         2     pLnS   ~0+x    contr_none    add      NA       NA      NA      NA     NA
   5         2     pB2    ~0+x    contr_none    add      NA       NA      NA      NA     NA
   6         2     pZ0    ~0+x    contr_none    add      NA       NA      NA      NA     NA
  END_PARAM_EQS
  FE_VALS
  pA
  pv_idx   par_idx  x        m     mirror phase   units     IV         LB        UB         prior         p1            p2
   1        1       male     imm     0     1     grams    0.00027     0.0001     0.0005     lognormal     0.00027       0.1
   2        1       male     mat     1                                        
   3        1       female   imm     0     1     grams    0.000562    0.0001     0.0006     lognormal     0.000562     0.1
   4        1       female   mat     0     1     grams    0.000441    0.0001     0.0006     lognormal     0.000441     0.1
  END_pA
  pB1
  pv_idx   par_idx  x        m     mirror phase  units     IV         LB     UB     prior         p1           p2
   1        2       male     imm     0     1     none     3.022134    1       6     lognormal     3.022134     0.1
   2        2       male     mat     1                                        
   3        2       female   imm     0     1     none     2.816928    1       6     lognormal     2.816928     0.1
   4        2       female   mat     0     1     none     2.898686    1       6     lognormal     2.898686     0.1
  END_pB1
  pLnA
  pv_idx   par_idx  x     mirror phase   units     tform       IV          LB         UB         prior         p1        p2
   1        3       male   0      1      grams     log         0.00027     0.0001     0.0005     normal     0.00027      0.1
  END_pLnA
  pLnS
  pv_idx   par_idx  x     mirror phase   units     IV
   1        4       male   0     -1      none      0 
  END_pLnS
  pB2
  pv_idx   par_idx  x     mirror phase   units     IV         LB     UB     prior      p1           p2
   1        5       male   0      1      none      3.022134    1     6      lognormal  3.022134     0.1
  END_pB2
  pZ0
  pv_idx   par_idx  x     mirror phase   units     IV
   1        6       male   0     -1      mm_CW     1 
  END_pZ0
  END_FE_VALS
  END_ALLOMETRY
');
strv = str |> splitText() |> extractLines("PROCESS_ALLOMETRY","END_ALLOMETRY");
dfrFcns = strv |> extractLines("FUNCTIONS","END_FUNCTIONS")   |> evalTextAsDataframe();
dfrPEQs = strv |> extractLines("PARAM_EQS","END_PARAM_EQS")   |> evalTextAsDataframe();
par_ids = dfrPEQs$id;
##--fixed effects parameter values
strFEVs = strv |> extractLines("FE_VALS","END_FE_VALS");
lstFEVs = list();
if (length(strFEVs)>0){
  for (par_id in par_ids){
    strp = strFEVs |> extractLines(par_id,paste0("END_",par_id));
    lstFEVs[[par_id]]  = strp |> evalTextAsDataframe();
  }
}#--FEVs
##--random effects parameter values
strREVs = strv |> extractLines("RE_VALS","END_RE_VALS");
lstREVs = list();
if (length(strREVs)>0){
  for (par_id in par_ids){
    strp = strREVs |> extractLines(par_id,paste0("END_",par_id));
    lstREVs[[par_id]]  = strp |> evalTextAsDataframe();
  }
}#--REVs
##--environmental covariates parameter values
strECVs = strv |> extractLines("EC_VALS","END_EC_VALS");
lstECVs = list();
if (length(strECVs)>0){
  for (par_id in par_ids){
    strp = strECVs |> extractLines(par_id,paste0("END_",par_id));
    lstECVs[[par_id]]  = strp |> evalTextAsDataframe();
  }
}#--ECVs
```

```{r}
#| label: refs_CTL-Allometry
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  cat("# References {-}\n")
  cat("::: {#refs}\n")
  cat(":::\n\n")
```

<!-- tables, if not child doc and lstTbls is not empty -->
```{r}
#| label: tables_CTL-Allometry
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printTablesSectionFromList.R",package="wtsQMD"));
```

<!-- figures, if not child doc and lstFigs is not empty -->
```{r}
#| label: figures_CTL-Allometry
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printFiguresSectionFromList.R",package="wtsQMD"));
```

