---
title: "Input Data"
author:
- name: William T. Stockhausen
  affiliations:
    - id: afsc-refm
      name: "Alaska Fisheries Science Center"
      department: "Resource Ecology and Fisheries Management"
      address: 
        - "7600 Sand Point Way N.E."
        - "Seattle, Washington 98115-6349"
crossref: 
  fig-title: Figure
  tbl-title: Table
comment: "#>"
collapse: true
toc: true
format: 
  html: 
    html-math-method: mathjax
tbl-cap-location: top
fig-cap-location: bottom
prefer-html: true
keep-md: false
keep-yaml: false
---

<!--NOTE: for scalar variables,    use: *var*   (italics)  
          for vectors/matrices,etc use: ***V*** (bold-italics) 
          for functions            use: **fcn** (bold) 
          for verbatim code        use: `code` 
-->

```{r setup,echo=FALSE}
  suppressPackageStartupMessages(require(rtmbGMACS));
```

## Input files

The ADMB version of gmacs required four files to define and run a model: the "gmacs.dat" file, a data file (the "dat" file), a control file (the "ctl" file), and a projection file (the "prj" file). As discussed below, these files can be read using functions available in the rtmbGMACS package, simplifying conversion of models from ADMB to RTMB.

### The "gmacs.dat" file

A "gmacs.dat" can be read using the `readDatFile` function. This file specifies the filenames of the dat, ctl, and prj files for a model run, as well as other information such as stock name, units of weight and abundance, and various options for running the ADMB model. The `readADMB_DatFile` function returns the information from this file as a named list, with elements 

  * `input files`: a character vector with the path/filenames for the "dat", "ctl", and "prj" files
  * `units`: a named character vector specifying units for biomass (`wgt`) and abundance (`num`)
  * `stock`: the name of the crab stock
  * `jitter info`: a numeric vector with elements
    - [1]: a flag indicating whether (1) or not (0) to jitter the initial parameter values
    - [2]: the standard deviation for the jitter randomization
  * `variances to export`: a numeric vector with values indicating whether (1) or not (0) to include uncertainty estimates for
    - reference points
    - recruits
    - SSB
    - Fbar
    - OutDynB0
  * `retro peel`: the number of years to "peel back" the model end year for a retrospective model run
  * `other`: a named list with elements specifying other options for the model run

The returned list has an attribute "type" set to "admb dat file inputs".

### The "dat" file

The "dat" file includes all the data to be included in an ADMB gmacs model run. The ADMB version of gmacs is capable of including the following data types in the model optimization:

  - fishery catch and effort time series data
  - index (survey or fishery cpue) biomass and abundance time series data
  - size composition data
  - growth (molt increment) data
  - maturity ogive data
  - tagging data (for growth)
  - environmental data time series
  
Data files created for the ADMB version of gmacs can be read using the package function 
`readADMB_DataFile`. The result is 

### The "ctl" file

The "ctl" file 

### The "prj" file

The "prj" file 
`readADMB_PrjFile`

